---
title: "ImmigAppBuilder"
author: "ethan"
date: "2022-12-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(ggalluvial)
library(ggplot2)
```

```{r}
LPR2011 = read.csv('csvs/LPRAdjustmentTypes11to20.csv')
LPR2011
```


```{r}
longTry = pivot_longer(data = tryDF, !NaturalizedRegion2011, names_to = 'state', values_to = 'naturalized')
longTry
```


```{r, fig.height=12, fig.width=6}
ggplot(longTry,
       aes(y = naturalized, axis1 = NaturalizedRegion2011, axis2 = state)) +
  geom_alluvium(aes(fill = NaturalizedRegion2011), width = .1) +
  geom_stratum(width = .1, aes(fill = NaturalizedRegion2011)) +
  geom_label(stat = "stratum", aes(label = after_stat(stratum))) +
  ggtitle("2011 Naturalization by Region of Birth and State of Residence") +
  theme_bw()
```

```{r}
natz2016 = read.csv('csvs/NaturalizationRegionState2016.csv')
natz2016
```

```{r}
natz = natz2016[2:7, c('NaturalizedRegion2016', 'Arizona', 'California', 'Texas', 'Florida', 'Virginia', 'New.York', 'Massachusetts', 'Illinois','Maryland', 'Michigan', 'Minnesota', 'New.Jersey', 'North.Carolina', 'Pennsylvania', 'Washington')]
natz
```
```{r}
natz = pivot_longer(natz, !NaturalizedRegion2016, names_to = 'state', values_to = 'naturalized')
natz
```



```{r, fig.height=12, fig.width=6}
ggplot(natz,
       aes(y = naturalized, axis2 = NaturalizedRegion2016, axis1 = state)) +
  geom_alluvium(aes(fill = NaturalizedRegion2016), width = .1) +
  geom_stratum(width = .1, aes(fill = NaturalizedRegion2016)) +
  geom_label(stat = "stratum", aes(label = after_stat(stratum))) +
  ggtitle("2016 Naturalization by Region of Birth and State of Residence") +
  theme_bw()
```

In the shiny app, it takes too long to load 36 small DF's at the start, so I'll make 2 big ones instead (one for LPR, one for natz)

```{r}
dir('csvs/')[9:43]
```

```{r}
read.csv('csvs/lpr05.csv')
```

```{r}
longlprs = data.frame()
longnats = data.frame()
for (yr in as.character(2005:2021)){
  lpr = read.csv(paste0('csvs/longlpr', substr(yr, 3, 4), '.csv'))
  nat = read.csv(paste0('csvs/longnatz', substr(yr, 3, 4), '.csv'))
  lpr$year = rep(yr, dim(lpr)[1])
  nat$year = rep(yr, dim(nat)[1])
  longlprs = rbind(longlprs, lpr)
  longnats = rbind(longnats, nat)
}
```

```{r}
write.csv(longlprs %>% select(-c(X.1)), 'csvs/longlprs.csv')
write.csv(longnats %>% select(-c(X.1)), 'csvs/longnats.csv')
```







